### ISSUE TITLE
circleStyle and containerStyle throws an error

### ISSUE THREAD

**Issue by DimitrisTzimikas** [react-native-seoul/react-native-switch-toggle#6]
```
<SwitchToggle
          switchOn={this.state.switchOn}
          onPress={this.onPress}
          backgroundColorOn='#faa519'
          backgroundColorOff='#e5e1e0'
          circleColorOn={'white'}
          circleColorOff={'white'}
          circleStyle={{ width: 25, height: 25, borderRadius: 15, padding: 1 }}
          containerStyle={{ width: 60, height: 20, borderRadius: 20, padding: 1}}
/>
````

When I load the screen I get an error:

Error while updating property 'transform' of a view managed by: RCTView

null

translateX 
.
.
.

If I change the default props from library on index.js everything works fine. Any suggestions?

**Comment by DimitrisTzimikas** [comment]
False alarm. I write the props like the example. So this format seems to be working: 

```
<SwitchToggle
          circleStyle={{
            width: 25,
            height: 25,
            borderRadius: 15,
          }}
          containerStyle={{
            width: 60,
            height: 20,
            borderRadius: 20,
            padding: 1,
          }}
          switchOn={this.state.switchOn}
          onPress={this.onPress}
          backgroundColorOn='#faa519'
          backgroundColorOff='#e5e1e0'
          circleColorOn={'white'}
          circleColorOff={'white'}
/>
```

I don't know if it was the format of the code, or the order, or the emulators fault. Anyhow, if I'm missing something correct me.

**Comment by dooboolab** [comment]
Are you still suffering? If you've solved this could you share this by giving us a `PR`?

**Comment by DimitrisTzimikas** [comment]
@dooboolab everything works fine in "react-native-switch-toggle": "^1.0.6"

**Comment by dooboolab** [comment]
Thank you for the confirm. Then I will close this.
